# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: R
cache: packages
latex: false
sudo: false
warnings_are_errors: false
# fd332e6a-f3bf-4d60-83d3-65c28196a20e
r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
